services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-nexteshop_pwd}
      POSTGRES_DB: nexteshop
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    ports:
      - "8686:3000"
    environment:
      DATABASE_URL: postgresql://postgres:${DB_PASSWORD:-nexteshop_pwd}@db:5432/nexteshop
      NEXTAUTH_URL: ${NEXTAUTH_URL:-https://nexteshop.com}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-super_secret_key_123}
      # MercadoPago
      MP_ACCESS_TOKEN: ${MP_ACCESS_TOKEN}
      MP_CLIENT_ID: ${MP_CLIENT_ID}
      MP_CLIENT_SECRET: ${MP_CLIENT_SECRET}
    depends_on:
      - db

volumes:
  postgres_data:
